apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-controller
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
        - path: /api/poi
          backend:
            serviceName: poi-service
            servicePort: 80
    - http:
        paths:
        - path: /api/trips
          backend:
            serviceName: trips-service
            servicePort: 80
    - http:
        paths:
        - path: /api/user
          backend:
            serviceName: userprofile-service
            servicePort: 80
    - http:
        paths:
        - path: /api/user-java
          backend:
            serviceName: userjava-service
            servicePort: 80
    - http:
        paths:
        - path: /
          backend:
            serviceName: tripviewer-service
            servicePort: 80
      