apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi-api
  template:
    metadata:
      labels:
        app: poi-api
    spec:
      containers:
      - name: poi
        image: registryzks1348.azurecr.io/poi:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: poi-api
---


