apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi-api
  template:
    metadata:
      labels:
        app: poi-api
    spec:
      containers:
      - name: poi
        image: registryzks1348.azurecr.io/poi:v1
        ports:
        - containerPort: 80
        env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: SQL_SERVER
              value: sqlserverzks1348.database.windows.net
            - name: SQL_USER
              value: sqladminzKs1348
            - name: SQL_PASSWORD
              value: gB2hf9Vg0
        resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: poi-api
---


