apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips-api
  template:
    metadata:
      labels:
        app: trip-api
    spec:
      containers:
      - name: trips
        image: registryzks1348.azurecr.io/trips:v1
        ports:
        - containerPort: 80
        env:
            - name: CONFIG_FILES_PATH
              value: /secrets
            - name: SQL_USER
              value: sqladminzKs1348
            - name: SQL_PASSWORD
              value: gB2hf9Vg0
            - name: SQL_SERVER
              value: sqlserverzks1348.database.windows.net
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: OPENAPI_DOCS_URI
              value: http://trips-service
        resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: trips-api
---