apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile-api
  template:
    metadata:
      labels:
        app: userprofile-api
    spec:
      containers:
      - name: userprofile
        image: registryzks1348.azurecr.io/userprofile:v1
        ports:
        - containerPort: 80
        env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: SQL_SERVER
              value: sqlserverzks1348.database.windows.net
            - name: SQL_USER
              value: sqladminzKs1348
            - name: SQL_PASSWORD
              value: gB2hf9Vg0
            - name: CONFIG_FILES_PATH
              value: /secrets
        resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 500Mi
            
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: userprofile-api
---


